server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/publishinn
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: publishinn2021@gmail.com
    password: zaq1@WSX34
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
